[[main]]
none = "none"

# [[main]]
# name = "Broder"
# pre = "telegram"
# url = "https://t.me/odanbroder"
# identifier = "xjbHd89Rrz"
# weight = 1

[[main]]
name = "Tags"
pre = "hackernews"
pageRef = "tags"
identifier = "GwwselvCn3"
weight = 9999

[[footer]]
none = "none"

# [[footer]]
# name = "Broder"
# url = "https://github.com/OdanBroder"
# identifier = "DnxHxrR2Ba"
# weight = 9999

[[footer]]
name = "Linkedln"
url = "https://www.linkedin.com/in/duc-anh-doan-67abb0333/"
identifier = "pCuGBkJdN0"
weight = 9999
